---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/sabnzbd:/config"
      - "${MEDIA_DIR}:/media"
    ports:
      - 8080:8080
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${MEDIA_DIR}:/media"
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - sabnzbd
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
      - "${MEDIA_DIR}:/media"
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - sabnzbd
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"
      - "${MEDIA_DIR}:/media"
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - sabnzbd
  transmission:
    cap_add:
      - NET_ADMIN
    volumes:
      - "${CONFIG_DIR}/transmission:/config"
      - "${MEDIA_DIR}:/media"
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_USERNAME=${MULLVAD_USER}
      - OPENVPN_PASSWORD=m
      - OPENVPN_CONFIG=au_all
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/media/download/torrent/complete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/media/download/torrent/incomplete
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    logging:
      driver: json-file
      options:
          max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/perth
      - PORT=5055 #optional
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_DIR}/overseerr:/app/config
    restart: unless-stopped
  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      - TZ=Australia/perth
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CONFIG_DIR}/proxy/data:/data
      - ${CONFIG_DIR}/proxy/letsencrypt:/etc/letsencrypt
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/perth
    ports:
      - 8181:8181
