---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/sabnzbd:/config"
      - "${MEDIA_DIR}:/media"
      - "${DL_DIR}:/download"
    ports:
      - 8080:8080
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${MEDIA_DIR}:/media"
      - "${DL_DIR}:/download"
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - sabnzbd
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
      - "${MEDIA_DIR}:/media"
      - "${DL_DIR}:/download"
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - sabnzbd
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"
      - "${MEDIA_DIR}:/media"
      - "${DL_DIR}:/download"
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - sabnzbd
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - "${CONFIG_DIR}/deluge:/config"
      - "${DL_DIR}:/download"
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/perth
      - PORT=5055 #optional
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_DIR}/overseerr:/app/config
    restart: unless-stopped
  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      - TZ=Australia/perth
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CONFIG_DIR}/proxy/data:/data
      - ${CONFIG_DIR}/proxy/letsencrypt:/etc/letsencrypt
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/perth
    ports:
      - 8181:8181
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - "${CONFIG_DIR}/flaresolverr:/config"
    ports:
      - 8191:8191
    restart: unless-stopped
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
      - UN_LOG_FILE=/config/unpackerr.log
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
    volumes:
      - "${CONFIG_DIR}/unpackerr:/config"
      - "${DL_DIR}:/download"
    restart: unless-stopped